"""First aid situations. Each step is (short instruction, detail) or
(short instruction, detail, illustration key from illustrations.py)."""

SEV = {
    "red":   {"label": "Life-threatening - call 112 first", "color": "#C8102E"},
    "kids":  {"label": "Babies and children - call 112 first", "color": "#C8102E"},
    "amber": {"label": "Urgent", "color": "#F2A516", "ink": "#B45A00"},
    "teal":  {"label": "Common", "color": "#11695A"},
}

CARDS = [
    {
        "id": "cpr", "sev": "red", "title": "Not breathing (adult)", "sub": "Unresponsive, no normal breathing",
        "keys": "cpr cardiac arrest collapse unconscious no pulse heart stopped reanimation",
        "recognize": "Doesn't respond when you shout and tap the shoulders, and isn't breathing normally (gasping doesn't count).",
        "call": True, "metronome": True,
        "steps": [
            ("Make sure it's safe", "Check for traffic, electricity, fire, gas before you approach."),
            ("Check response", "Tap the shoulders firmly and shout: “Are you OK?”"),
            ("Open the airway, check breathing", "Tilt the head back, lift the chin. Look, listen and feel for normal breathing for up to 10 seconds."),
            ("Call 112 on speaker", "Stay with the person. Send someone to bring an AED (defibrillator) if there is one nearby."),
            ("Push hard and fast", "Heel of your hand in the centre of the chest, other hand on top, arms straight. Press 5-6 cm deep, 100-120 times a minute. Let the chest rise fully between pushes.", "cpr_adult"),
            ("30 pushes, then 2 breaths", "If trained: tilt head, pinch nose, 2 breaths of 1 second each. If not trained or unwilling: just keep pushing without stopping."),
            ("Use the AED as soon as it arrives", "Switch it on and follow the spoken instructions. Keep pushing while the pads are being placed."),
            ("Don't stop", "Continue until help takes over, the person starts breathing normally, or you are physically unable to go on. Swap with another person every 2 minutes if possible."),
        ],
        "when": ["Always - call 112 immediately"],
        "dont": ["Don't stop compressions to check for a pulse",
                 "Don't be afraid of hurting them - broken ribs heal, cardiac arrest doesn't"],
    },
    {
        "id": "choking", "sev": "red", "title": "Choking (adult)", "sub": "Adult or teenager",
        "keys": "choking choke airway obstruction food stuck cant breathe heimlich",
        "recognize": "Suddenly can't speak, cough or breathe; often grabs the throat.",
        "steps": [
            ("Ask “Are you choking?”", "If they can cough strongly, encourage them to keep coughing and stay with them."),
            ("Up to 5 back blows", "Stand to the side, lean them forward, support the chest. Give firm blows between the shoulder blades with the heel of your hand. Check after each blow.", "back_blows"),
            ("Up to 5 abdominal thrusts", "Stand behind, fist just above the belly button, other hand over it. Pull sharply inward and upward. Check after each thrust.", "abdominal"),
            ("Repeat", "Alternate 5 back blows and 5 thrusts until the object comes out."),
            ("Call 112 if it isn't cleared", "Keep going while someone calls."),
            ("If they become unresponsive", "Lower them to the ground, call 112, and start CPR (see ‘Not breathing’)."),
        ],
        "when": ["Object not cleared after 3 rounds", "They become unresponsive",
                 "After any abdominal thrusts - they need a medical check"],
        "dont": ["Don't do blind finger sweeps in the mouth",
                 "Don't hit the back of someone who is coughing effectively"],
    },
    {
        "id": "drowning", "sev": "red", "title": "Drowning", "sub": "Pulled from the water",
        "keys": "drowning drowned water pool sea lake swimming",
        "recognize": "Person pulled from water who is unresponsive, not breathing normally, or coughing and struggling to breathe.",
        "call": True, "metronome": True,
        "steps": [
            ("Don't become a second victim", "Reach with a pole or throw something that floats. Only go into the water if you are trained and it's safe."),
            ("Get them out and call 112", "Keep them lying flat. Put the phone on speaker."),
            ("Open the airway, check breathing", "Tilt the head back, lift the chin. Look, listen and feel for up to 10 seconds."),
            ("Not breathing? Give 5 rescue breaths first", "Pinch the nose, 5 breaths of 1 second each. Drowning is a breathing problem, so breaths matter more than in other collapses."),
            ("Then CPR: 30 compressions, 2 breaths", "Centre of the chest, 5-6 cm deep, 100-120 a minute. For a child or baby, use the child or baby card.", "cpr_adult"),
            ("If they vomit", "Turn them on their side, let it drain, clear the mouth, then continue."),
            ("Breathing? Recovery position, keep warm", "Remove wet clothes if you can and cover them. Keep checking breathing.", "recovery"),
        ],
        "when": ["Always - even if they seem fine; breathing problems can develop hours later"],
        "dont": ["Don't try to get water out of the lungs - no abdominal thrusts, no hanging upside down",
                 "Don't swim out unless you are trained"],
    },
    {
        "id": "bleeding", "sev": "red", "title": "Severe bleeding", "sub": "Blood spurting or soaking through",
        "keys": "bleeding blood cut wound hemorrhage haemorrhage tourniquet stab",
        "recognize": "Blood is pumping or flowing fast, or soaking through clothes.",
        "call": True,
        "steps": [
            ("Protect yourself", "Use gloves or a plastic bag over your hand if available."),
            ("Press hard on the wound", "Use a clean cloth, bandage or your hand. Press firmly and don't let go."),
            ("Call 112", "Or get someone else to call while you keep pressing."),
            ("Keep pressing for at least 10 minutes", "If blood soaks through, add more cloth on top - don't remove the first layer."),
            ("Bandage firmly", "Once bleeding slows, wrap tightly over the pad. Check fingers/toes stay warm and pink."),
            ("Tourniquet for limb bleeding that won't stop", "Only for arms/legs: 5-7 cm above the wound, tighten until bleeding stops, note the time."),
            ("Lay them down, keep warm", "Watch for pale, cold, clammy skin and confusion - signs of shock."),
        ],
        "when": ["Bleeding doesn't stop with pressure", "Spurting blood", "Deep wound, or something stuck in it"],
        "dont": ["Don't remove an object stuck in the wound - press around it", "Don't lift the pad to check"],
    },
    {
        "id": "allergy", "sev": "red", "title": "Severe allergic reaction", "sub": "Anaphylaxis",
        "keys": "allergy allergic anaphylaxis bee sting nuts swelling epipen adrenaline",
        "recognize": "Fast swelling of lips, tongue or throat, difficulty breathing, wheezing, hives, dizziness - often after food, a sting or medicine.",
        "call": True,
        "steps": [
            ("Use their adrenaline auto-injector", "Outer thigh, through clothes if needed. Follow the instructions on the pen."),
            ("Call 112", "Say “anaphylaxis”."),
            ("Position", "Lie them down with legs raised. If breathing is hard, let them sit up. Don't make them stand or walk."),
            ("Second dose after 5 minutes", "If there's no improvement and a second pen is available."),
            ("Watch breathing", "If they become unresponsive and stop breathing normally, start CPR."),
        ],
        "when": ["Always, even if the pen works - symptoms can return"],
        "dont": ["Don't wait to see if it gets worse", "Don't make them stand up suddenly"],
    },
    {
        "id": "electric", "sev": "red", "title": "Electric shock", "sub": "Electricity, lightning",
        "keys": "electric shock electrocution electricity socket cable power line lightning",
        "recognize": "Person found near a cable, socket or appliance, or after lightning; may be unresponsive, burned, confused.",
        "call": True,
        "steps": [
            ("Don't touch them yet", "While they are still in contact with the current, the electricity can pass to you."),
            ("Switch off the power", "Unplug the appliance or switch off at the fuse box."),
            ("Can't switch off? Push away with something dry", "Stand on dry wood, rubber or a thick book. Use a dry wooden broom or chair to move the cable or the person. Only for household electricity."),
            ("Power lines: stay back", "Keep at least 18 metres away and call 112. Don't approach until the power company says it's off."),
            ("Call 112", "Every serious electric shock needs a hospital check, even if they seem fine."),
            ("Check breathing", "Not breathing: start CPR and use an AED. Breathing: recovery position."),
            ("Cool burns", "Cool entry and exit burns under running water for 20 minutes, then cover loosely."),
        ],
        "when": ["High voltage or lightning", "Any loss of consciousness", "Burns",
                 "Chest pain, irregular heartbeat, confusion", "Pregnant"],
        "dont": ["Don't touch the person until the power is off", "Don't use anything wet or metal",
                 "Don't go near fallen power lines"],
    },
    {
        "id": "accident", "sev": "red", "title": "Road accident", "sub": "Car, motorbike, pedestrian hit",
        "keys": "road accident car crash traffic accident collision crash motorbike motorcycle helmet hit by a car pedestrian vehicle trapped",
        "recognize": "A crash involving a car, motorbike, bicycle or pedestrian. People may be injured, trapped, unconscious or bleeding, and there may be traffic, fuel or fire.",
        "call": True,
        "steps": [
            ("Make yourself safe first", "Stop well away from the crash, switch on the hazard lights and put on a reflective vest. Place the warning triangle well behind the scene - at least 30 m, further on fast roads. Watch out for traffic."),
            ("Call 112", "Say exactly where you are (road, direction, kilometre sign or landmark), how many vehicles and injured people there are, and whether anyone is trapped, or there's fire or leaking fuel."),
            ("Make the vehicles safe", "Switch off the engines if you can. No smoking. If there's fire or a strong smell of fuel, keep everyone away."),
            ("Don't move the injured", "Unless they are in immediate danger, such as fire or traffic. Assume a neck or back injury: ask them to stay still and hold the head in line with the body."),
            ("Help the most serious first", "Not breathing: start CPR (see ‘Not breathing’). Heavy bleeding: press hard on the wound. Unconscious but breathing in a seat: support the head and keep the airway open - move them only if the airway is at risk."),
            ("Motorcyclist: leave the helmet on", "Remove it only if they aren't breathing and you can't open the airway otherwise - ideally with two people, keeping the head and neck in line."),
            ("Keep them warm and stay with them", "Cover them with a coat or blanket, talk to them calmly, and watch their breathing until help arrives."),
        ],
        "when": ["Always - anyone injured, trapped or unconscious needs an ambulance"],
        "dont": ["Don't move the injured unless there's immediate danger",
                 "Don't remove a motorcycle helmet unless it's needed to help them breathe",
                 "Don't give food or drink",
                 "Don't stand or run in the traffic lanes"],
    },
    {
        "id": "unconscious", "sev": "red", "title": "Unconscious but breathing", "sub": "Recovery position",
        "keys": "unconscious recovery position passed out breathing faint lateral",
        "recognize": "Doesn't respond, but is breathing normally.",
        "call": True,
        "steps": [
            ("Check breathing", "Tilt the head back, lift the chin, and confirm normal breathing for up to 10 seconds."),
            ("Call 112", "Put the phone on speaker so your hands stay free."),
            ("Roll onto the side", "Arm nearest you at a right angle. Other hand against their cheek. Bend the far knee, pull it toward you so they roll onto their side.", "recovery"),
            ("Keep the airway open", "Tilt the head back slightly so the mouth points down and fluids can drain."),
            ("Keep checking breathing", "Check every minute. If breathing stops, roll them on their back and start CPR (see ‘Not breathing’)."),
            ("Keep them warm", "Cover with a coat or blanket until help arrives."),
        ],
        "when": ["Always - anyone unconscious needs an ambulance"],
        "dont": ["Don't give food or drink", "Don't leave them alone",
                 "Don't move them if you suspect a neck or spine injury - only roll if the airway is at risk"],
    },
    {
        "id": "shock", "sev": "red", "title": "Shock", "sub": "Pale, cold, clammy after injury",
        "keys": "shock circulatory shock pale clammy cold sweat fast pulse blood loss collapse weak dizzy",
        "recognize": "Pale, cold, clammy skin; fast, weak pulse; fast, shallow breathing; dizzy, weak, thirsty, anxious or confused - usually after heavy bleeding, a serious injury, burns, severe vomiting or diarrhoea, or an allergic reaction.",
        "call": True,
        "steps": [
            ("Call 112", "Shock can get worse quickly, even if they seem fine at first."),
            ("Treat the cause", "Stop any bleeding by pressing hard on the wound (see ‘Severe bleeding’). For a severe allergic reaction, use their adrenaline pen (see ‘Severe allergic reaction’)."),
            ("Lay them down", "Flat on their back, on a blanket or coat if possible."),
            ("Raise the legs", "Lift the legs slightly if there's no injury to the legs, hips, neck or back and it doesn't cause pain. Don't do it if breathing gets harder."),
            ("Keep them warm", "Cover with a coat or blanket. Loosen tight clothing at the neck, chest and waist."),
            ("Reassure and monitor", "Stay with them, keep them calm, and check their breathing and response regularly."),
            ("If unresponsive", "Breathing: recovery position. Not breathing normally: start CPR (see ‘Not breathing’)."),
        ],
        "when": ["Always - shock is a medical emergency"],
        "dont": ["Don't give food or drink - they may need surgery; wet the lips if they're thirsty",
                 "Don't let them get up or walk around", "Don't leave them alone",
                 "Don't use a hot-water bottle or heater - just stop them losing heat"],
    },
    {
        "id": "heart", "sev": "red", "title": "Heart attack", "sub": "Chest pain or pressure",
        "keys": "heart attack chest pain pressure myocardial infarction angina arm pain",
        "recognize": "Pain, pressure or tightness in the chest, possibly spreading to arm, jaw, neck or back. Sweating, nausea, shortness of breath.",
        "call": True,
        "steps": [
            ("Call 112", "Say you suspect a heart attack."),
            ("Sit them down", "Half-sitting, knees bent, leaning against something. Loosen tight clothes."),
            ("Aspirin", "If not allergic and not told by a doctor to avoid it: one adult aspirin (150-300 mg), chewed slowly."),
            ("Their own medicine", "If they carry nitroglycerin spray/tablets, help them take it."),
            ("Stay and monitor", "Keep them calm. If they become unresponsive and stop breathing normally, start CPR (see ‘Not breathing’)."),
        ],
        "when": ["Always - don't wait to see if it passes"],
        "dont": ["Don't let them walk or drive to hospital", "Don't give aspirin to children"],
    },
    {
        "id": "stroke", "sev": "red", "title": "Stroke", "sub": "Face, arm or speech problems",
        "keys": "stroke fast face droop arm weakness speech slurred brain",
        "recognize": "F.A.S.T. - Face drooping on one side, Arm weakness (can't lift both), Speech slurred or confused, Time to call.",
        "call": True,
        "steps": [
            ("Check F.A.S.T.", "Ask them to smile, raise both arms, and repeat a simple sentence."),
            ("Call 112 immediately", "Say “stroke” - every minute counts."),
            ("Note the time", "Remember when symptoms started or when they were last seen well. Doctors need this."),
            ("Keep them comfortable", "Sitting or lying with head and shoulders slightly raised. Reassure them."),
            ("If unresponsive", "Put in the recovery position if breathing; start CPR if not."),
        ],
        "when": ["Any one F.A.S.T. sign - even if it goes away"],
        "dont": ["Don't give food, drink or medicine", "Don't wait for symptoms to improve"],
    },
    {
        "id": "heatstroke", "sev": "red", "title": "Heat stroke", "sub": "Overheating, sunstroke",
        "keys": "heat stroke heatstroke sunstroke overheating hot sun exhaustion temperature fever summer",
        "recognize": "Very hot body after heat or exercise, confused or behaving strangely, headache, dizziness, may collapse. Skin may be dry or sweaty.",
        "call": True,
        "steps": [
            ("Call 112", "Confusion in the heat is an emergency."),
            ("Move to a cool place", "Shade, an air-conditioned room, out of the sun."),
            ("Remove extra clothing", "Down to light underclothes."),
            ("Cool fast", "Best: put the body in cold water up to the neck. Otherwise soak them with cold water and fan hard, and put cold packs on the neck, armpits and groin."),
            ("Sips of cool water", "Only if fully alert and able to swallow."),
            ("If unresponsive", "Recovery position if breathing, CPR if not. Keep cooling."),
        ],
        "when": ["Confused, drowsy or collapsed", "Seizure", "Not better within 15 minutes of cooling"],
        "dont": ["Don't give drinks if they are confused or vomiting",
                 "Don't give paracetamol or aspirin - they don't lower heat-stroke temperature",
                 "Don't stop cooling because they start shivering"],
    },
    {
        "id": "poisoning", "sev": "red", "title": "Poisoning", "sub": "Swallowed, breathed in, on skin",
        "keys": "poison poisoning swallowed pills overdose tablets chemicals bleach cleaning mushrooms gas carbon monoxide fumes",
        "recognize": "Swallowed medicine, chemicals, plants or mushrooms; breathed in gas or fumes; or chemicals on the skin or in the eyes. May be drowsy, vomiting, confused or in pain.",
        "call": True,
        "steps": [
            ("Protect yourself", "Gas or fumes: open windows, get them to fresh air, don't go in if it's unsafe. Wear gloves for chemicals."),
            ("Call 112", "Say what was taken, how much and when. Keep the packet, bottle or plant to show the paramedics."),
            ("Chemicals on skin", "Remove soaked clothes. Rinse the skin with lots of running water for at least 20 minutes."),
            ("Chemicals in the eye", "Rinse with running water for 15-20 minutes, holding the eye open."),
            ("Swallowed something burning", "Let them rinse the mouth with water and spit it out."),
            ("If unresponsive", "Recovery position if breathing. Not breathing: CPR - use compressions only if there's poison on the lips."),
        ],
        "when": ["Always for poisoning - the operator will advise"],
        "dont": ["Don't make them vomit", "Don't give milk, salt water or anything to drink unless told to",
                 "Don't give activated charcoal unless a doctor says so"],
    },
    {
        "id": "cpr-child", "sev": "kids", "title": "Not breathing (child)", "sub": "Age 1 year to puberty",
        "keys": "child kid toddler cpr cardiac arrest not breathing unconscious drowning reanimation",
        "recognize": "Child doesn't respond when you speak loudly and tap them, and isn't breathing normally.",
        "call": True, "metronome": True,
        "steps": [
            ("Make sure it's safe", "Check for traffic, water, electricity before you approach."),
            ("Check response", "Tap the child and speak loudly: “Are you OK?”"),
            ("Call 112 on speaker", "Shout for help. If you have a phone, call 112 now and put it on speaker. No phone? Do 1 minute of CPR first, then go and call."),
            ("Open the airway, check breathing", "Tilt the head back gently and lift the chin. Look, listen and feel for normal breathing for up to 10 seconds."),
            ("Give 5 rescue breaths", "Pinch the nose, seal your mouth over theirs, blow steadily for about 1 second - just enough to make the chest rise."),
            ("Give 15 chest compressions", "Heel of one hand (or two hands for a bigger child) on the lower half of the breastbone. Press about 5 cm - one third of the chest depth - 100-120 times a minute.", "cpr_child"),
            ("Continue 2 breaths, 15 compressions", "Keep repeating without long pauses. If you can't or won't give breaths, keep doing compressions only - it's much better than nothing."),
            ("Use the AED as soon as it arrives", "Switch it on and follow the voice. Use child pads or child mode if it has them; otherwise adult pads are fine."),
        ],
        "when": ["Always - call 112 immediately"],
        "dont": ["Don't skip the 5 first breaths if you're able to give them - children usually stop breathing before the heart stops",
                 "Don't stop to check for a pulse"],
    },
    {
        "id": "cpr-infant", "sev": "kids", "title": "Not breathing (baby)", "sub": "Under 1 year",
        "keys": "baby infant newborn cpr not breathing unconscious limp blue reanimation",
        "recognize": "Baby is limp, doesn't react when you touch or speak to them, and isn't breathing normally.",
        "call": True, "metronome": True,
        "steps": [
            ("Check response", "Speak loudly and gently tap the sole of the foot. Don't shake the baby."),
            ("Call 112 on speaker", "Shout for help. If you have a phone, call 112 now and put it on speaker. No phone? Do 1 minute of CPR first, then call - carry the baby with you if you can."),
            ("Open the airway - head level", "Lay the baby on their back on a firm surface. Keep the head in a neutral position (nose pointing up), not tilted back. Lift the chin with one finger."),
            ("Check breathing", "Look, listen and feel for normal breathing for up to 10 seconds."),
            ("Give 5 rescue breaths", "Cover the baby's mouth AND nose with your mouth. Give gentle puffs of about 1 second - just enough to make the chest rise."),
            ("Give 15 chest compressions", "Two fingers on the lower half of the breastbone (just below the nipple line). Press about 4 cm - one third of the chest depth - 100-120 times a minute.", "cpr_infant"),
            ("Continue 2 breaths, 15 compressions", "Keep repeating. If you can't give breaths, keep doing compressions only."),
            ("Use an AED if one arrives", "Follow the voice. Use child pads or child mode if available - one pad on the chest, one on the back if the pads don't fit on the front."),
        ],
        "when": ["Always - call 112 immediately"],
        "dont": ["Don't tilt the head far back - a baby's airway is soft and can close",
                 "Don't shake the baby", "Don't blow hard - gentle puffs from your cheeks are enough"],
    },
    {
        "id": "choking-child", "sev": "kids", "title": "Choking (child)", "sub": "Age 1 year to puberty",
        "keys": "child kid toddler choking choke food toy stuck cant breathe heimlich",
        "recognize": "Child suddenly can't speak, cry, cough or breathe; may turn red or blue, grab the throat.",
        "steps": [
            ("Is the cough strong?", "If the child can cough loudly, encourage coughing and stay close. Don't hit the back."),
            ("Shout for help, call 112 on speaker", "Keep your hands free for the child."),
            ("Up to 5 back blows", "Kneel or stand behind/beside the child, lean them forward. Firm blows between the shoulder blades with the heel of your hand. Check after each blow.", "back_blows"),
            ("Up to 5 abdominal thrusts", "Kneel or stand behind. Fist just above the belly button, other hand over it. Pull sharply inward and upward. Check after each thrust.", "abdominal"),
            ("Repeat", "Alternate 5 back blows and 5 thrusts until the object comes out or the child becomes unresponsive."),
            ("If the child becomes unresponsive", "Lay them down and start CPR - see ‘Not breathing (child)’, starting with 5 breaths."),
        ],
        "when": ["Object doesn't come out quickly", "Child becomes unresponsive",
                 "After any abdominal thrusts - the child needs a medical check"],
        "dont": ["Don't do blind finger sweeps - you can push the object deeper; only remove it if you clearly see it",
                 "Don't hold the child upside down by the legs"],
    },
    {
        "id": "choking-infant", "sev": "kids", "title": "Choking (baby)", "sub": "Under 1 year",
        "keys": "baby infant newborn choking choke milk food toy cant breathe blue",
        "recognize": "Baby suddenly can't cry, cough or breathe; silent, struggling, turning blue.",
        "steps": [
            ("Is the cough strong?", "If the baby is coughing or crying loudly, let them cough and watch closely."),
            ("Shout for help, call 112 on speaker", "Keep your hands free for the baby."),
            ("Up to 5 back blows", "Lay the baby face down along your forearm, head lower than the body. Hold the jaw with your fingers (don't press the soft throat). Give firm blows between the shoulder blades with the heel of your hand.", "back_blows_infant"),
            ("Up to 5 chest thrusts", "Turn the baby face up along your other forearm, head still lower. Two fingers on the lower half of the breastbone (same place as CPR). Push sharply down 5 times.", "cpr_infant"),
            ("Repeat", "Alternate 5 back blows and 5 chest thrusts. Check the mouth - remove the object only if you can clearly see it."),
            ("If the baby becomes unresponsive", "Start CPR - see ‘Not breathing (baby)’, starting with 5 breaths."),
        ],
        "when": ["Object doesn't come out quickly", "Baby becomes unresponsive",
                 "After any back blows or chest thrusts - the baby needs a medical check"],
        "dont": ["Don't give abdominal thrusts to a baby - they can damage the organs",
                 "Don't do blind finger sweeps in the mouth",
                 "Don't hold the baby upside down by the legs or shake them"],
    },
    {
        "id": "febrile", "sev": "kids", "title": "Fever seizure (child)", "sub": "Fit with high temperature, 6 months to 5 years",
        "keys": "febrile seizure febrile convulsion fever fit child baby toddler temperature high fever shaking jerking seizure convulsion",
        "recognize": "A child aged 6 months to 5 years with a fever suddenly goes stiff, the eyes roll, arms and legs jerk, and the child doesn't respond. May turn pale or bluish. Usually stops within 1-2 minutes.",
        "steps": [
            ("Note the time", "Check how long the seizure lasts. Stay calm - most fever seizures stop on their own and don't cause harm."),
            ("Lay the child down safely", "On a soft surface, on their side if you can, away from hard or sharp objects. Don't hold them down."),
            ("Nothing in the mouth", "Don't put fingers, a spoon or anything else in the mouth. The child can't swallow their tongue."),
            ("Call 112 if needed", "Call if it's the first seizure, it lasts more than 5 minutes, or the child struggles to breathe. If a doctor has given you emergency seizure medicine, use it as instructed."),
            ("When the jerking stops", "Put the child on their side (recovery position) and check breathing. They may be sleepy or confused for up to an hour.", "recovery"),
            ("Don't let them overheat", "Remove extra clothes and blankets. Keep the room at a normal temperature."),
            ("Fever medicine once fully awake", "When the child is awake and can swallow, paracetamol or ibuprofen in the dose for their age or weight can make them more comfortable."),
            ("See a doctor", "Every fever seizure should be checked by a doctor, even a short one, to find the cause of the fever."),
        ],
        "when": ["First seizure ever", "Lasts more than 5 minutes", "Another seizure soon after",
                 "Breathing difficulty, or lips stay blue after the seizure",
                 "Doesn't wake up properly within an hour",
                 "Stiff neck, or a rash that doesn't fade when you press a glass on it",
                 "Baby younger than 6 months"],
        "dont": ["Don't put anything in the mouth", "Don't hold the child down or shake them",
                 "Don't put the child in a cold bath or rub with cold water or alcohol",
                 "Don't give food, drink or medicine by mouth until fully awake"],
    },
    {
        "id": "asthma", "sev": "amber", "title": "Asthma attack", "sub": "Wheezing, can't catch breath",
        "keys": "asthma attack wheezing wheeze inhaler puffer breathless shortness of breath tight chest",
        "recognize": "Person with asthma who is wheezing, coughing, has a tight chest, and struggles to breathe or to speak in full sentences.",
        "steps": [
            ("Sit them upright", "Sitting up, leaning slightly forward - not lying down. Loosen tight clothing and keep them calm."),
            ("Help them use their reliever inhaler", "Usually the blue one. Shake it, then 1 puff every 30-60 seconds, up to 10 puffs. Use a spacer if they have one."),
            ("Slow breathing", "Encourage slow, steady breaths. Stay calm yourself - panic makes breathing harder."),
            ("No better after 10 puffs? Call 112", "Call at once too if they are getting worse, too breathless to speak, or their lips turn blue."),
            ("Repeat while you wait", "If help hasn't arrived after 10 minutes, give up to 10 more puffs the same way."),
            ("If they become unresponsive", "Not breathing normally: start CPR (see ‘Not breathing’)."),
        ],
        "when": ["No better after 10 puffs", "Too breathless to speak, eat or sleep",
                 "Lips or fingertips turning blue or grey", "Exhausted, drowsy or confused",
                 "No inhaler available and breathing is hard"],
        "dont": ["Don't lay them down", "Don't put a paper bag over their mouth", "Don't leave them alone"],
    },
    {
        "id": "sugar", "sev": "amber", "title": "Low blood sugar", "sub": "Diabetic emergency",
        "keys": "diabetes diabetic hypo hypoglycemia low sugar insulin shaky sweating",
        "recognize": "Known diabetic who is shaky, sweaty, pale, confused, irritable or unusually drowsy.",
        "steps": [
            ("Is the person awake and able to swallow?", "If not - go to ‘Unconscious but breathing’ and call 112."),
            ("Give fast sugar", "Glucose tablets, a glass of juice or regular (not diet) soft drink, or a few sweets."),
            ("Wait 10-15 minutes", "Let them sit and rest."),
            ("No better? Give sugar again", "Repeat once."),
            ("When they feel better", "Give a snack with slower carbs - bread, biscuit, banana."),
        ],
        "when": ["Unconscious or can't swallow", "No improvement after 2 doses of sugar", "Seizure"],
        "dont": ["Don't give food or drink to someone who can't swallow safely", "Don't give insulin"],
    },
    {
        "id": "seizure", "sev": "amber", "title": "Seizure", "sub": "Convulsions, fit",
        "keys": "seizure fit convulsion epilepsy shaking epileptic",
        "recognize": "Sudden stiffening and jerking movements, may fall, not aware of surroundings.",
        "steps": [
            ("Note the time", "Check how long the seizure lasts."),
            ("Protect from injury", "Move hard or sharp objects away. Cushion the head with something soft."),
            ("Let it happen", "Don't hold them down. Loosen anything tight around the neck."),
            ("After shaking stops", "Check breathing and put them in the recovery position.", "recovery"),
            ("Stay with them", "Talk calmly - they may be confused or sleepy for a while."),
        ],
        "when": ["Seizure lasts more than 5 minutes", "Another seizure follows", "First-ever seizure",
                 "Injured, pregnant, in water, or doesn't wake up"],
        "dont": ["Don't put anything in their mouth", "Don't restrain movements",
                 "Don't give food or drink until fully alert"],
    },
    {
        "id": "snakebite", "sev": "amber", "title": "Snake bite", "sub": "Viper, adder",
        "keys": "snake bite bitten snakebite viper adder serpent venom poisonous snake fang",
        "recognize": "Two small puncture marks, with pain, swelling and bruising spreading from the bite. Later there may be nausea, vomiting, dizziness, swelling of the face or trouble breathing. In Bulgaria the venomous snakes are vipers (пепелянка, усойница).",
        "call": True,
        "steps": [
            ("Move away from the snake", "Don't try to catch or kill it. If it's safe, take a photo from a distance - it helps the doctors."),
            ("Call 112", "Every viper bite needs a hospital check, even if it doesn't hurt much at first."),
            ("Keep them still and calm", "Sit or lay them down. Movement spreads the venom faster. Don't let them walk if they can be carried or picked up."),
            ("Remove rings, watches and tight things", "From the bitten arm or leg, before it swells - including shoes."),
            ("Keep the limb still", "Support it with a sling or splint, roughly at the level of the heart."),
            ("Note the time and mark the swelling", "Write down when the bite happened. Draw a line with a pen at the edge of the swelling and write the time next to it - doctors use this to see how fast it spreads."),
            ("Watch for a serious reaction", "Swelling of the face, trouble breathing or collapse: use the ‘Severe allergic reaction’ or ‘Shock’ card. Not breathing normally: start CPR."),
        ],
        "when": ["Always - every snake bite needs a hospital check",
                 "Child, elderly person, or bite on the face or neck",
                 "Swelling spreading fast, vomiting, dizziness, fainting or trouble breathing"],
        "dont": ["Don't cut the wound or try to suck out the venom",
                 "Don't use a tourniquet or a tight bandage",
                 "Don't put ice on the bite",
                 "Don't give alcohol, aspirin or ibuprofen",
                 "Don't try to catch or kill the snake"],
    },
    {
        "id": "burn", "sev": "amber", "title": "Burns", "sub": "Heat, hot water, fire",
        "keys": "burn scald fire hot water heat blister",
        "recognize": "Red, painful, blistered or white/charred skin.",
        "steps": [
            ("Stop the burning", "Move away from the source. Remove from heat."),
            ("Cool with running water for 20 minutes", "Cool or lukewarm tap water, as soon as possible."),
            ("Remove jewellery and clothing", "Near the burn - unless stuck to the skin."),
            ("Cover loosely", "Cling film laid on (not wrapped tightly) or a clean plastic bag."),
            ("Keep the person warm", "Cool the burn, not the person - watch for shivering, especially children."),
        ],
        "when": ["Larger than their palm", "Face, hands, feet, genitals or joints", "Chemical or electrical burn",
                 "White, charred or painless skin", "Burns in children or elderly"],
        "dont": ["Don't use ice, butter, oil, toothpaste or creams", "Don't pop blisters",
                 "Don't use fluffy cotton on the burn"],
    },
    {
        "id": "hypothermia", "sev": "amber", "title": "Hypothermia", "sub": "Body too cold",
        "keys": "hypothermia cold freezing frozen shivering cold water winter snow exposure chilled",
        "recognize": "Has been out in the cold or in cold water. Shivering, pale cold skin, clumsy, slurred speech, confused or drowsy. In severe cases the shivering stops.",
        "steps": [
            ("Get out of the cold", "Move them indoors or into shelter. Protect from wind and put something underneath to insulate them from the ground."),
            ("Call 112 if it's serious", "Confused, drowsy, slurred speech or no longer shivering - call 112 now."),
            ("Handle gently", "Move them carefully and keep them lying down if they are drowsy or very cold - rough handling can upset the heartbeat."),
            ("Replace wet clothes", "Take off wet clothing and put on dry layers. Cover the head and neck."),
            ("Wrap them up", "Blankets, a sleeping bag, coats, with a foil blanket on the outside. Body-to-body contact under the blankets helps."),
            ("Warm the core of the body", "Warm (not hot) packs wrapped in cloth on the chest, armpits and groin - not on the arms and legs."),
            ("Warm sweet drink", "Only if fully alert and able to swallow. Hot chocolate or sweet tea - no alcohol."),
            ("If unresponsive", "Check breathing for up to 1 minute - it can be very slow. Breathing: recovery position, keep warming. Not breathing normally: call 112 and start CPR."),
        ],
        "when": ["Confused, drowsy or slurred speech", "Stopped shivering while still cold", "Unresponsive",
                 "Pulled from cold water", "Elderly person or baby who is very cold", "Not warming up despite help"],
        "dont": ["Don't rub or massage the arms and legs",
                 "Don't use a hot bath, a hot-water bottle directly on the skin, or a heater close to the skin",
                 "Don't give alcohol",
                 "Don't make them walk if they are very cold - move them gently"],
    },
    {
        "id": "frostbite", "sev": "amber", "title": "Frostbite", "sub": "Fingers, toes, ears, nose from cold",
        "keys": "frostbite frostnip frozen fingers toes ears nose cheeks cold numb white skin winter snow mountain",
        "recognize": "After time in the cold, fingers, toes, ears, nose or cheeks turn white, grey or waxy, feel hard and cold, with pins and needles and then no feeling. When they warm up they may turn red, swell and blister.",
        "steps": [
            ("Check for hypothermia first", "Shivering hard, confused, drowsy or slurred speech? Use the ‘Hypothermia’ card first - the whole body comes before fingers and toes."),
            ("Get to a warm place", "Move into shelter. Remove wet clothing, and gently take off rings, watches and tight boots before swelling starts."),
            ("Don't warm it if it could freeze again", "Thawing and refreezing does more damage. Keep the area protected until you reach a place where it can stay warm."),
            ("Rewarm in warm water", "Put the area in warm water - comfortable to your elbow, about 37-39 °C, not hot - for 20-30 minutes, until the skin is soft and the colour comes back. No water? Use body heat, such as hands in the armpits. It can be very painful."),
            ("Handle gently, no rubbing", "Don't rub or massage the skin. Avoid walking on frostbitten feet if you can."),
            ("Dry and cover loosely", "Pat dry, cover with a loose, clean dressing and put gauze or cloth between fingers and toes. Keep the limb raised. Paracetamol or ibuprofen can help with pain."),
            ("Get medical help", "See a doctor for anything more than skin that recovers fully in a few minutes - especially if it stays white, hard or numb, or blisters appear."),
        ],
        "when": ["Signs of hypothermia - confused, drowsy, slurred speech",
                 "Skin stays white, grey, blue or black, or stays hard after warming",
                 "Blisters, especially filled with blood",
                 "Large areas affected, or the face"],
        "dont": ["Don't rub with snow or your hands",
                 "Don't use a fire, heater, hairdryer or hot-water bottle to warm it",
                 "Don't burst blisters",
                 "Don't warm it if it might freeze again",
                 "Don't give alcohol or let them smoke"],
    },
    {
        "id": "head", "sev": "amber", "title": "Head injury", "sub": "Blow to the head, concussion",
        "keys": "head injury concussion hit head fall bump skull knocked out",
        "recognize": "Blow to the head from a fall, hit or accident. Bump, cut, headache, dizziness, confusion or a short blackout.",
        "steps": [
            ("Keep them still", "If there could be a neck injury (fall from height, car, diving), hold the head still in line with the body and don't move them."),
            ("Unresponsive?", "Call 112. Breathing: keep the airway open; only roll them if they vomit. Not breathing: CPR."),
            ("Stop bleeding", "Scalp wounds bleed a lot. Press with a clean cloth. If you feel a dent in the skull, press around it, not on it."),
            ("Cold pack on the bump", "Wrapped in a cloth, 10-20 minutes."),
            ("Watch them for 24 hours", "Don't leave them alone. Check they wake easily and answer normally. Look for the danger signs below."),
        ],
        "when": ["Knocked out, even briefly", "Confused, very drowsy or hard to wake", "Vomiting more than once",
                 "Seizure", "Blood or clear fluid from the nose or ears", "Weakness, numbness, slurred speech or blurred vision",
                 "Headache getting worse", "Takes blood thinners", "Fall from height or car accident",
                 "Baby or young child with a big bump, or not behaving normally"],
        "dont": ["Don't give alcohol or sleeping pills", "Don't let them drive or do sport the same day",
                 "Don't move them if you suspect a neck injury"],
    },
    {
        "id": "eye", "sev": "amber", "title": "Eye injury", "sub": "Chemical, speck, blow to the eye",
        "keys": "eye injury eyes chemical in eye something in eye dust speck grit eyelash splinter hit in eye black eye vision bleach cement lime",
        "recognize": "A chemical, dust or a small object got into the eye, or the eye was hit or cut. Pain, redness, watering, blurred vision, or the eye won't open.",
        "steps": [
            ("Don't rub the eye", "Rubbing can scratch the eye or push dirt deeper. Wash your hands before you touch the area."),
            ("Chemical? Rinse at once for 20 minutes", "Start immediately - every second counts. Hold the eye open and pour clean, lukewarm running water from the inner corner outward, so it doesn't run into the other eye. Take out contact lenses if they come out easily."),
            ("Then call 112", "For any chemical in the eye. Keep rinsing while you wait, and keep the bottle or packaging to show the paramedics."),
            ("Something stuck in the eye? Don't pull it out", "Don't press on the eye. Cover it loosely with a paper cup or a clean pad, ask the person to keep both eyes as still as possible, and call 112."),
            ("Dust or an eyelash? Blink and rinse", "Blink a few times and rinse with clean water or saline. If you can see it on the white of the eye, lift it off gently with the corner of a clean, wet cloth. Never touch the coloured part of the eye."),
            ("Blow to the eye? Cold pack, no pressure", "Cold pack wrapped in a cloth, held lightly against the eye for 10-15 minutes."),
            ("See a doctor", "After any chemical, cut or hard blow, or if pain, redness or blurred vision don't settle soon."),
        ],
        "when": ["Any chemical in the eye - especially cement, lime, bleach or drain cleaner",
                 "Something stuck in the eye", "Cut to the eye or eyelid",
                 "Sudden loss of vision, or seeing flashes or a dark curtain",
                 "Blood inside the eye, or the eye looks misshapen"],
        "dont": ["Don't rub or press on the eye",
                 "Don't try to remove anything stuck in the eye",
                 "Don't put drops, ointment, milk or anything other than clean water in the eye",
                 "Don't touch the coloured part of the eye"],
    },
    {
        "id": "animalbite", "sev": "amber", "title": "Dog or animal bite", "sub": "Dog, cat, wild animal",
        "keys": "dog bite animal bite bitten cat bite scratch stray dog fox bat wild animal rabies tetanus wound",
        "recognize": "A bite or deep scratch from a dog, cat or other animal - puncture wounds, torn skin or bleeding. Stray dogs, foxes, bats and other wild animals carry the highest risk of rabies.",
        "steps": [
            ("Get away from the animal", "Move to safety. Don't try to catch the animal yourself. If it has an owner, ask whether it is vaccinated against rabies."),
            ("Heavy bleeding? Press first", "Press hard on the wound with a clean cloth and call 112 (see ‘Severe bleeding’)."),
            ("Wash the wound for 15 minutes", "With soap and lots of running water, even if the bite is small. This is the most important step against rabies and infection."),
            ("Disinfect and cover", "Apply an antiseptic (for example iodine) and cover with a clean dressing. Don't close the wound with strips or glue."),
            ("See a doctor the same day", "For every bite that breaks the skin. The doctor decides about rabies and tetanus vaccines and antibiotics - rabies vaccine only works if started early."),
            ("Note details about the animal", "What animal, where it happened, whether it had an owner and the owner's contacts, and whether it behaved strangely. An owned animal is usually observed for 10 days."),
            ("Watch for infection", "Over the next days, see a doctor again if there is spreading redness, swelling, warmth, pus, red streaks or fever."),
        ],
        "when": ["Bleeding that doesn't stop with pressure",
                 "Many or deep wounds, especially in a child",
                 "Bite on the face or neck",
                 "Pale, cold, clammy skin or confusion (signs of shock)"],
        "dont": ["Don't ignore a small bite - even small punctures can carry infection or rabies",
                 "Don't close the wound with tape, strips or glue",
                 "Don't try to catch or kill the animal",
                 "Don't wait to see a doctor - rabies vaccine must start early"],
    },
    {
        "id": "faint", "sev": "teal", "title": "Fainting", "sub": "Short loss of consciousness",
        "keys": "faint fainted dizzy lightheaded passed out syncope",
        "recognize": "Feels lightheaded, pale, sweaty, then collapses briefly.",
        "steps": [
            ("Lay them flat", "If they feel faint, help them lie down before they fall."),
            ("Raise the legs", "Lift the legs about 30 cm on a bag or chair."),
            ("Give them air", "Loosen tight clothing, ask people to step back, open a window."),
            ("Wait for recovery", "Most people come round within a minute. Help them sit up slowly."),
            ("If they don't wake up", "Check breathing: recovery position if breathing, CPR if not. Call 112."),
        ],
        "when": ["Not awake within 1-2 minutes", "Chest pain, palpitations, or fainting during exercise",
                 "Injured when falling, pregnant, or over 50"],
        "dont": ["Don't sit them up quickly", "Don't splash water or slap the face"],
    },
    {
        "id": "fracture", "sev": "teal", "title": "Broken bone", "sub": "Fracture, sprain",
        "keys": "fracture broken bone sprain twisted ankle leg arm",
        "recognize": "Pain, swelling, bruising, odd shape or angle, can't move the limb.",
        "steps": [
            ("Keep it still", "Support the injured part in the position you found it."),
            ("Stop any bleeding", "If the bone is through the skin, press around it with a clean cloth - not on the bone."),
            ("Immobilise", "Support with padding, a sling (arm) or tie to the other leg with padding between."),
            ("Cold pack", "Ice wrapped in a cloth, 10-20 minutes. Never ice directly on skin."),
            ("Get medical help", "Hospital for an X-ray. Call 112 for major bones or if they can't be moved."),
        ],
        "when": ["Bone through the skin", "Thigh, hip, pelvis, neck or back injury",
                 "Limb is cold, pale or numb below the injury"],
        "dont": ["Don't try to straighten the bone", "Don't let them eat or drink (they may need surgery)",
                 "Don't move them if you suspect neck/back injury"],
    },
    {
        "id": "nosebleed", "sev": "teal", "title": "Nosebleed", "sub": "Bleeding from the nose",
        "keys": "nosebleed nose bleed blood epistaxis",
        "recognize": "Blood running from one or both nostrils.",
        "steps": [
            ("Sit up and lean forward", "So blood runs out of the nose, not down the throat."),
            ("Pinch the soft part of the nose", "Just below the bony bridge. Breathe through the mouth."),
            ("Hold for 10-15 minutes", "Without letting go to check. Use a clock."),
            ("Spit out blood", "Swallowed blood can make them vomit."),
            ("Still bleeding? Another 10 minutes", "A cold pack on the bridge of the nose can help."),
            ("After it stops", "Don't blow or pick the nose, and avoid heavy effort for 24 hours."),
        ],
        "when": ["Bleeding for more than 20 minutes", "After a blow to the head or face",
                 "Very heavy bleeding or trouble breathing", "Takes blood thinners"],
        "dont": ["Don't tilt the head back", "Don't lie down", "Don't push tissue deep into the nose"],
    },
    {
        "id": "cuts", "sev": "teal", "title": "Cuts and grazes", "sub": "Small wounds, scrapes",
        "keys": "cut cuts graze grazes scrape scratch small wound abrasion plaster band-aid knife finger knee skinned bleeding a little",
        "recognize": "A small cut, scrape or graze that bleeds a little. If blood is spurting or soaking through, use the ‘Severe bleeding’ card.",
        "steps": [
            ("Wash your hands", "Use gloves if you have them."),
            ("Stop the bleeding", "Press on the wound with a clean cloth or gauze for 5-10 minutes. Raise it if it's on an arm or leg."),
            ("Clean the wound", "Rinse under clean running tap water. Gently wash out dirt and gravel - especially from a graze, so it doesn't get infected."),
            ("Dry and cover", "Pat the skin around it dry. You can use an antiseptic, then cover with a plaster or a non-stick dressing."),
            ("Change the dressing", "Every day, or sooner if it gets wet or dirty. Keep the wound clean and dry."),
            ("Does it need stitches?", "See a doctor within a few hours if the edges gape open, it's deep or longer than about 2 cm, or it's on the face, a joint or the hand."),
            ("Tetanus", "Dirty wound (soil, rust, animal) and no tetanus shot in the last 5 years, or not sure? See a doctor about a booster."),
            ("Watch for infection", "See a doctor if redness spreads, it swells, feels hot, has pus or red streaks, or there is fever."),
        ],
        "when": ["Bleeding doesn't stop after 10 minutes of firm pressure",
                 "Blood is spurting",
                 "Something is stuck deep in the wound"],
        "dont": ["Don't put cotton wool directly on the wound - the fibres stick",
                 "Don't pour alcohol or hydrogen peroxide into the wound",
                 "Don't pull out an object stuck deep in the wound - press around it",
                 "Don't blow on the wound"],
    },
    {
        "id": "tick", "sev": "teal", "title": "Tick bite", "sub": "Tick stuck in the skin",
        "keys": "tick bite tick ticks embedded lyme borreliosis bug insect attached spotted fever",
        "recognize": "A small dark bug stuck firmly in the skin, often in the armpits, groin, behind the knees or ears, at the waistline, or on a child's scalp.",
        "steps": [
            ("Remove it as soon as possible", "The longer a tick stays attached, the higher the risk of infection."),
            ("Grip it close to the skin", "Use fine-pointed tweezers or a tick remover. Grab the tick by the head, as close to the skin as you can - not by the body."),
            ("Pull straight out, slowly and steadily", "Don't twist or jerk. If you use a tick hook or card, follow its instructions."),
            ("Part left in the skin?", "Try to remove it with the tweezers. If you can't easily, leave it - the skin will push it out as it heals."),
            ("Clean the bite and your hands", "Soap and water or an antiseptic."),
            ("Note the date", "Write down the date and where on the body the bite was. Check the whole body for more ticks, including children and pets."),
            ("Watch the bite for 30 days", "See a doctor if a red rash grows around the bite (often a ring or ‘bull's-eye’), a dark spot forms at the bite, or there is fever, headache, muscle aches or tiredness."),
        ],
        "when": ["High fever with bleeding from the gums or nose, or unusual bruising",
                 "Severe headache, stiff neck or confusion",
                 "Swelling of the face or trouble breathing"],
        "dont": ["Don't squeeze or crush the tick's body",
                 "Don't put oil, butter, alcohol or nail polish on the tick, and don't burn it",
                 "Don't dig deep into the skin for leftover parts"],
    },
    {
        "id": "tape", "sev": "teal", "title": "Kinesio taping", "sub": "Sprain or strain: ankle, knee, wrist, shoulder, back",
        "keys": "kinesio tape kinesiology tape taping tape sprain strain sprained twisted ankle knee wrist shoulder lower back muscle pull support",
        "recognize": "For a mild sprain (twisted joint) or strain (pulled muscle) after the first check. The tape can give comfort and a feeling of support, but it doesn't heal the injury - evidence that it speeds recovery is limited.",
        "steps": [
            ("First: sprain, not a break?", "See a doctor before taping if you can't put weight on it or take 4 steps, the bone itself hurts when you press it, the joint looks deformed, or there is a lot of swelling or bruising."),
            ("First 48 hours: rest, cold, support, raise", "Rest the joint. Cold pack wrapped in a cloth for 10-20 minutes every 2-3 hours. Elastic bandage for support. Keep it raised."),
            ("Prepare the skin and the tape", "Skin clean, dry and without cream; trim thick hair. Measure the strips on the stretched joint, cut them and round off the corners with scissors so they don't peel. Apply 30-60 minutes before sport or a shower."),
            ("The basic rule: ends without stretch", "Stick the first 3-5 cm (the anchor) with no stretch. Stretch only the middle part. Stick the last 3-5 cm again with no stretch. Never wrap the tape all the way around an arm or leg. Rub it firmly for a few seconds - warmth activates the glue."),
            ("Ankle", "Foot at a right angle. Strip 1: stick the end on the inner side of the lower leg, about a hand above the ankle bone. Run it down under the heel and up the outer side, with about half stretch over the outer ankle bone, and finish on the outer lower leg. Strip 2: from the top of the foot on the inner side, around the back of the heel just above it, to the top of the foot on the outer side, with light stretch - the ends must not meet.", "tape_ankle"),
            ("Knee", "Sit with the knee bent. Cut a strip about 30 cm long down the middle, leaving 5 cm uncut (a Y). Stick the uncut end on the front of the thigh about a hand above the kneecap. Run the two tails around each side of the kneecap with light stretch and stick the ends below it. Optional: a short strip across just below the kneecap, half stretch in the middle. Pain on the inner or outer side of the knee? First put two short strips in an X over the painful side, crossing at the level of the joint, with half stretch in the middle - then the Y on top.", "tape_knee"),
            ("Wrist", "Bend the wrist down, palm toward the floor. Strip 1: from the back of the hand, just below the knuckles, along the back of the forearm for about 15 cm, light stretch. Strip 2: across the back of the wrist, half stretch in the middle, ends on the sides - not meeting on the palm side.", "tape_wrist"),
            ("Shoulder", "Sit with the arm hanging. Cut a Y-strip about 25 cm long. Stick the uncut end on the outer upper arm, about a third of the way down. Move the arm back and lay the front tail over the front of the shoulder to the top. Move the arm forward across the chest and lay the back tail over the back of the shoulder to the top. Light stretch on both tails.", "tape_shoulder"),
            ("Lower back", "Bend forward as far as is comfortable. Stick two strips of about 25 cm, one on each side of the spine (on the muscles, not the bone), from just above the buttocks upward, with light stretch. Optional: a short strip across the most painful spot, half stretch in the middle.", "tape_back"),
            ("Wearing and removing", "Tape can stay on 3-5 days, and you can shower - pat it dry. Remove it slowly in the direction of hair growth, pressing the skin down next to it; soaking it with oil first helps. Take it off at once if the skin itches, burns or tingles, or the pain gets worse."),
        ],
        "when": ["Bone through the skin, or the joint looks deformed",
                 "Arm or leg below the injury is cold, pale or numb"],
        "dont": ["Don't tape over wounds, broken or irritated skin, or a suspected fracture",
                 "Don't wrap the tape all the way around a limb",
                 "Don't stretch the ends of the strips",
                 "Don't use it if you are allergic to plasters or adhesive",
                 "Don't use tape instead of a doctor for a bad injury"],
    },
]
