"""First aid situations. Each step is (short instruction, detail)."""

SEV = {
    "red":   {"label": "Life-threatening — call 112 first", "color": "#C8102E"},
    "kids":  {"label": "Babies and children — call 112 first", "color": "#C8102E"},
    "amber": {"label": "Urgent", "color": "#B45A00"},
    "teal":  {"label": "Common", "color": "#11695A"},
}

CARDS = [
    {
        "id": "cpr", "sev": "red", "title": "Not breathing (adult)", "sub": "Unresponsive, no normal breathing",
        "keys": "cpr cardiac arrest collapse unconscious no pulse heart stopped reanimation",
        "recognize": "Doesn't respond when you shout and tap the shoulders, and isn't breathing normally (gasping doesn't count).",
        "call": True, "metronome": True,
        "steps": [
            ("Make sure it's safe", "Check for traffic, electricity, fire, gas before you approach."),
            ("Check response", "Tap the shoulders firmly and shout: “Are you OK?”"),
            ("Open the airway, check breathing", "Tilt the head back, lift the chin. Look, listen and feel for normal breathing for up to 10 seconds."),
            ("Call 112 on speaker", "Stay with the person. Send someone to bring an AED (defibrillator) if there is one nearby."),
            ("Push hard and fast", "Heel of your hand in the centre of the chest, other hand on top, arms straight. Press 5–6 cm deep, 100–120 times a minute. Let the chest rise fully between pushes."),
            ("30 pushes, then 2 breaths", "If trained: tilt head, pinch nose, 2 breaths of 1 second each. If not trained or unwilling: just keep pushing without stopping."),
            ("Use the AED as soon as it arrives", "Switch it on and follow the spoken instructions. Keep pushing while the pads are being placed."),
            ("Don't stop", "Continue until help takes over, the person starts breathing normally, or you are physically unable to go on. Swap with another person every 2 minutes if possible."),
        ],
        "when": ["Always — call 112 immediately"],
        "dont": ["Don't stop compressions to check for a pulse",
                 "Don't be afraid of hurting them — broken ribs heal, cardiac arrest doesn't"],
    },
    {
        "id": "unconscious", "sev": "red", "title": "Unconscious but breathing", "sub": "Recovery position",
        "keys": "unconscious recovery position passed out breathing faint lateral",
        "recognize": "Doesn't respond, but is breathing normally.",
        "call": True,
        "steps": [
            ("Check breathing", "Tilt the head back, lift the chin, and confirm normal breathing for up to 10 seconds."),
            ("Call 112", "Put the phone on speaker so your hands stay free."),
            ("Roll onto the side", "Arm nearest you at a right angle. Other hand against their cheek. Bend the far knee, pull it toward you so they roll onto their side."),
            ("Keep the airway open", "Tilt the head back slightly so the mouth points down and fluids can drain."),
            ("Keep checking breathing", "Check every minute. If breathing stops, roll them on their back and start CPR (see ‘Not breathing’)."),
            ("Keep them warm", "Cover with a coat or blanket until help arrives."),
        ],
        "when": ["Always — anyone unconscious needs an ambulance"],
        "dont": ["Don't give food or drink", "Don't leave them alone",
                 "Don't move them if you suspect a neck or spine injury — only roll if the airway is at risk"],
    },
    {
        "id": "choking", "sev": "red", "title": "Choking (adult)", "sub": "Adult or teenager",
        "keys": "choking choke airway obstruction food stuck cant breathe heimlich",
        "recognize": "Suddenly can't speak, cough or breathe; often grabs the throat.",
        "steps": [
            ("Ask “Are you choking?”", "If they can cough strongly, encourage them to keep coughing and stay with them."),
            ("Up to 5 back blows", "Stand to the side, lean them forward, support the chest. Give firm blows between the shoulder blades with the heel of your hand. Check after each blow."),
            ("Up to 5 abdominal thrusts", "Stand behind, fist just above the belly button, other hand over it. Pull sharply inward and upward. Check after each thrust."),
            ("Repeat", "Alternate 5 back blows and 5 thrusts until the object comes out."),
            ("Call 112 if it isn't cleared", "Keep going while someone calls."),
            ("If they become unresponsive", "Lower them to the ground, call 112, and start CPR (see ‘Not breathing’)."),
        ],
        "when": ["Object not cleared after 3 rounds", "They become unresponsive",
                 "After any abdominal thrusts — they need a medical check"],
        "dont": ["Don't do blind finger sweeps in the mouth",
                 "Don't hit the back of someone who is coughing effectively"],
    },
    {
        "id": "bleeding", "sev": "red", "title": "Severe bleeding", "sub": "Blood spurting or soaking through",
        "keys": "bleeding blood cut wound hemorrhage haemorrhage tourniquet stab",
        "recognize": "Blood is pumping or flowing fast, or soaking through clothes.",
        "call": True,
        "steps": [
            ("Protect yourself", "Use gloves or a plastic bag over your hand if available."),
            ("Press hard on the wound", "Use a clean cloth, bandage or your hand. Press firmly and don't let go."),
            ("Call 112", "Or get someone else to call while you keep pressing."),
            ("Keep pressing for at least 10 minutes", "If blood soaks through, add more cloth on top — don't remove the first layer."),
            ("Bandage firmly", "Once bleeding slows, wrap tightly over the pad. Check fingers/toes stay warm and pink."),
            ("Tourniquet for limb bleeding that won't stop", "Only for arms/legs: 5–7 cm above the wound, tighten until bleeding stops, note the time."),
            ("Lay them down, keep warm", "Watch for pale, cold, clammy skin and confusion — signs of shock."),
        ],
        "when": ["Bleeding doesn't stop with pressure", "Spurting blood", "Deep wound, or something stuck in it"],
        "dont": ["Don't remove an object stuck in the wound — press around it", "Don't lift the pad to check"],
    },
    {
        "id": "heart", "sev": "red", "title": "Heart attack", "sub": "Chest pain or pressure",
        "keys": "heart attack chest pain pressure myocardial infarction angina arm pain",
        "recognize": "Pain, pressure or tightness in the chest, possibly spreading to arm, jaw, neck or back. Sweating, nausea, shortness of breath.",
        "call": True,
        "steps": [
            ("Call 112", "Say you suspect a heart attack."),
            ("Sit them down", "Half-sitting, knees bent, leaning against something. Loosen tight clothes."),
            ("Aspirin", "If not allergic and not told by a doctor to avoid it: one adult aspirin (150–300 mg), chewed slowly."),
            ("Their own medicine", "If they carry nitroglycerin spray/tablets, help them take it."),
            ("Stay and monitor", "Keep them calm. If they become unresponsive and stop breathing normally, start CPR (see ‘Not breathing’)."),
        ],
        "when": ["Always — don't wait to see if it passes"],
        "dont": ["Don't let them walk or drive to hospital", "Don't give aspirin to children"],
    },
    {
        "id": "stroke", "sev": "red", "title": "Stroke", "sub": "Face, arm or speech problems",
        "keys": "stroke fast face droop arm weakness speech slurred brain",
        "recognize": "F.A.S.T. — Face drooping on one side, Arm weakness (can't lift both), Speech slurred or confused, Time to call.",
        "call": True,
        "steps": [
            ("Check F.A.S.T.", "Ask them to smile, raise both arms, and repeat a simple sentence."),
            ("Call 112 immediately", "Say “stroke” — every minute counts."),
            ("Note the time", "Remember when symptoms started or when they were last seen well. Doctors need this."),
            ("Keep them comfortable", "Sitting or lying with head and shoulders slightly raised. Reassure them."),
            ("If unresponsive", "Put in the recovery position if breathing; start CPR if not."),
        ],
        "when": ["Any one F.A.S.T. sign — even if it goes away"],
        "dont": ["Don't give food, drink or medicine", "Don't wait for symptoms to improve"],
    },
    {
        "id": "allergy", "sev": "red", "title": "Severe allergic reaction", "sub": "Anaphylaxis",
        "keys": "allergy allergic anaphylaxis bee sting nuts swelling epipen adrenaline",
        "recognize": "Fast swelling of lips, tongue or throat, difficulty breathing, wheezing, hives, dizziness — often after food, a sting or medicine.",
        "call": True,
        "steps": [
            ("Use their adrenaline auto-injector", "Outer thigh, through clothes if needed. Follow the instructions on the pen."),
            ("Call 112", "Say “anaphylaxis”."),
            ("Position", "Lie them down with legs raised. If breathing is hard, let them sit up. Don't make them stand or walk."),
            ("Second dose after 5 minutes", "If there's no improvement and a second pen is available."),
            ("Watch breathing", "If they become unresponsive and stop breathing normally, start CPR."),
        ],
        "when": ["Always, even if the pen works — symptoms can return"],
        "dont": ["Don't wait to see if it gets worse", "Don't make them stand up suddenly"],
    },
    {
        "id": "cpr-child", "sev": "kids", "title": "Not breathing (child)", "sub": "Age 1 year to puberty",
        "keys": "child kid toddler cpr cardiac arrest not breathing unconscious drowning reanimation",
        "recognize": "Child doesn't respond when you speak loudly and tap them, and isn't breathing normally.",
        "call": True, "metronome": True,
        "steps": [
            ("Make sure it's safe", "Check for traffic, water, electricity before you approach."),
            ("Check response", "Tap the child and speak loudly: “Are you OK?”"),
            ("Call 112 on speaker", "Shout for help. If you have a phone, call 112 now and put it on speaker. No phone? Do 1 minute of CPR first, then go and call."),
            ("Open the airway, check breathing", "Tilt the head back gently and lift the chin. Look, listen and feel for normal breathing for up to 10 seconds."),
            ("Give 5 rescue breaths", "Pinch the nose, seal your mouth over theirs, blow steadily for about 1 second — just enough to make the chest rise."),
            ("Give 15 chest compressions", "Heel of one hand (or two hands for a bigger child) on the lower half of the breastbone. Press about 5 cm — one third of the chest depth — 100–120 times a minute."),
            ("Continue 2 breaths, 15 compressions", "Keep repeating without long pauses. If you can't or won't give breaths, keep doing compressions only — it's much better than nothing."),
            ("Use the AED as soon as it arrives", "Switch it on and follow the voice. Use child pads or child mode if it has them; otherwise adult pads are fine."),
        ],
        "when": ["Always — call 112 immediately"],
        "dont": ["Don't skip the 5 first breaths if you're able to give them — children usually stop breathing before the heart stops",
                 "Don't stop to check for a pulse"],
    },
    {
        "id": "cpr-infant", "sev": "kids", "title": "Not breathing (baby)", "sub": "Under 1 year",
        "keys": "baby infant newborn cpr not breathing unconscious limp blue reanimation",
        "recognize": "Baby is limp, doesn't react when you touch or speak to them, and isn't breathing normally.",
        "call": True, "metronome": True,
        "steps": [
            ("Check response", "Speak loudly and gently tap the sole of the foot. Don't shake the baby."),
            ("Call 112 on speaker", "Shout for help. If you have a phone, call 112 now and put it on speaker. No phone? Do 1 minute of CPR first, then call — carry the baby with you if you can."),
            ("Open the airway — head level", "Lay the baby on their back on a firm surface. Keep the head in a neutral position (nose pointing up), not tilted back. Lift the chin with one finger."),
            ("Check breathing", "Look, listen and feel for normal breathing for up to 10 seconds."),
            ("Give 5 rescue breaths", "Cover the baby's mouth AND nose with your mouth. Give gentle puffs of about 1 second — just enough to make the chest rise."),
            ("Give 15 chest compressions", "Two fingers on the lower half of the breastbone (just below the nipple line). Press about 4 cm — one third of the chest depth — 100–120 times a minute."),
            ("Continue 2 breaths, 15 compressions", "Keep repeating. If you can't give breaths, keep doing compressions only."),
            ("Use an AED if one arrives", "Follow the voice. Use child pads or child mode if available — one pad on the chest, one on the back if the pads don't fit on the front."),
        ],
        "when": ["Always — call 112 immediately"],
        "dont": ["Don't tilt the head far back — a baby's airway is soft and can close",
                 "Don't shake the baby", "Don't blow hard — gentle puffs from your cheeks are enough"],
    },
    {
        "id": "choking-child", "sev": "kids", "title": "Choking (child)", "sub": "Age 1 year to puberty",
        "keys": "child kid toddler choking choke food toy stuck cant breathe heimlich",
        "recognize": "Child suddenly can't speak, cry, cough or breathe; may turn red or blue, grab the throat.",
        "steps": [
            ("Is the cough strong?", "If the child can cough loudly, encourage coughing and stay close. Don't hit the back."),
            ("Shout for help, call 112 on speaker", "Keep your hands free for the child."),
            ("Up to 5 back blows", "Kneel or stand behind/beside the child, lean them forward. Firm blows between the shoulder blades with the heel of your hand. Check after each blow."),
            ("Up to 5 abdominal thrusts", "Kneel or stand behind. Fist just above the belly button, other hand over it. Pull sharply inward and upward. Check after each thrust."),
            ("Repeat", "Alternate 5 back blows and 5 thrusts until the object comes out or the child becomes unresponsive."),
            ("If the child becomes unresponsive", "Lay them down and start CPR — see ‘Not breathing (child)’, starting with 5 breaths."),
        ],
        "when": ["Object doesn't come out quickly", "Child becomes unresponsive",
                 "After any abdominal thrusts — the child needs a medical check"],
        "dont": ["Don't do blind finger sweeps — you can push the object deeper; only remove it if you clearly see it",
                 "Don't hold the child upside down by the legs"],
    },
    {
        "id": "choking-infant", "sev": "kids", "title": "Choking (baby)", "sub": "Under 1 year",
        "keys": "baby infant newborn choking choke milk food toy cant breathe blue",
        "recognize": "Baby suddenly can't cry, cough or breathe; silent, struggling, turning blue.",
        "steps": [
            ("Is the cough strong?", "If the baby is coughing or crying loudly, let them cough and watch closely."),
            ("Shout for help, call 112 on speaker", "Keep your hands free for the baby."),
            ("Up to 5 back blows", "Lay the baby face down along your forearm, head lower than the body. Hold the jaw with your fingers (don't press the soft throat). Give firm blows between the shoulder blades with the heel of your hand."),
            ("Up to 5 chest thrusts", "Turn the baby face up along your other forearm, head still lower. Two fingers on the lower half of the breastbone (same place as CPR). Push sharply down 5 times."),
            ("Repeat", "Alternate 5 back blows and 5 chest thrusts. Check the mouth — remove the object only if you can clearly see it."),
            ("If the baby becomes unresponsive", "Start CPR — see ‘Not breathing (baby)’, starting with 5 breaths."),
        ],
        "when": ["Object doesn't come out quickly", "Baby becomes unresponsive",
                 "After any back blows or chest thrusts — the baby needs a medical check"],
        "dont": ["Don't give abdominal thrusts to a baby — they can damage the organs",
                 "Don't do blind finger sweeps in the mouth",
                 "Don't hold the baby upside down by the legs or shake them"],
    },
    {
        "id": "seizure", "sev": "amber", "title": "Seizure", "sub": "Convulsions, fit",
        "keys": "seizure fit convulsion epilepsy shaking epileptic",
        "recognize": "Sudden stiffening and jerking movements, may fall, not aware of surroundings.",
        "steps": [
            ("Note the time", "Check how long the seizure lasts."),
            ("Protect from injury", "Move hard or sharp objects away. Cushion the head with something soft."),
            ("Let it happen", "Don't hold them down. Loosen anything tight around the neck."),
            ("After shaking stops", "Check breathing and put them in the recovery position."),
            ("Stay with them", "Talk calmly — they may be confused or sleepy for a while."),
        ],
        "when": ["Seizure lasts more than 5 minutes", "Another seizure follows", "First-ever seizure",
                 "Injured, pregnant, in water, or doesn't wake up"],
        "dont": ["Don't put anything in their mouth", "Don't restrain movements",
                 "Don't give food or drink until fully alert"],
    },
    {
        "id": "burn", "sev": "amber", "title": "Burns", "sub": "Heat, hot water, fire",
        "keys": "burn scald fire hot water heat blister",
        "recognize": "Red, painful, blistered or white/charred skin.",
        "steps": [
            ("Stop the burning", "Move away from the source. Remove from heat."),
            ("Cool with running water for 20 minutes", "Cool or lukewarm tap water, as soon as possible."),
            ("Remove jewellery and clothing", "Near the burn — unless stuck to the skin."),
            ("Cover loosely", "Cling film laid on (not wrapped tightly) or a clean plastic bag."),
            ("Keep the person warm", "Cool the burn, not the person — watch for shivering, especially children."),
        ],
        "when": ["Larger than their palm", "Face, hands, feet, genitals or joints", "Chemical or electrical burn",
                 "White, charred or painless skin", "Burns in children or elderly"],
        "dont": ["Don't use ice, butter, oil, toothpaste or creams", "Don't pop blisters",
                 "Don't use fluffy cotton on the burn"],
    },
    {
        "id": "sugar", "sev": "amber", "title": "Low blood sugar", "sub": "Diabetic emergency",
        "keys": "diabetes diabetic hypo hypoglycemia low sugar insulin shaky sweating",
        "recognize": "Known diabetic who is shaky, sweaty, pale, confused, irritable or unusually drowsy.",
        "steps": [
            ("Is the person awake and able to swallow?", "If not — go to ‘Unconscious but breathing’ and call 112."),
            ("Give fast sugar", "Glucose tablets, a glass of juice or regular (not diet) soft drink, or a few sweets."),
            ("Wait 10–15 minutes", "Let them sit and rest."),
            ("No better? Give sugar again", "Repeat once."),
            ("When they feel better", "Give a snack with slower carbs — bread, biscuit, banana."),
        ],
        "when": ["Unconscious or can't swallow", "No improvement after 2 doses of sugar", "Seizure"],
        "dont": ["Don't give food or drink to someone who can't swallow safely", "Don't give insulin"],
    },
    {
        "id": "faint", "sev": "teal", "title": "Fainting", "sub": "Short loss of consciousness",
        "keys": "faint fainted dizzy lightheaded passed out syncope",
        "recognize": "Feels lightheaded, pale, sweaty, then collapses briefly.",
        "steps": [
            ("Lay them flat", "If they feel faint, help them lie down before they fall."),
            ("Raise the legs", "Lift the legs about 30 cm on a bag or chair."),
            ("Give them air", "Loosen tight clothing, ask people to step back, open a window."),
            ("Wait for recovery", "Most people come round within a minute. Help them sit up slowly."),
            ("If they don't wake up", "Check breathing: recovery position if breathing, CPR if not. Call 112."),
        ],
        "when": ["Not awake within 1–2 minutes", "Chest pain, palpitations, or fainting during exercise",
                 "Injured when falling, pregnant, or over 50"],
        "dont": ["Don't sit them up quickly", "Don't splash water or slap the face"],
    },
    {
        "id": "fracture", "sev": "teal", "title": "Broken bone", "sub": "Fracture, sprain",
        "keys": "fracture broken bone sprain twisted ankle leg arm",
        "recognize": "Pain, swelling, bruising, odd shape or angle, can't move the limb.",
        "steps": [
            ("Keep it still", "Support the injured part in the position you found it."),
            ("Stop any bleeding", "If the bone is through the skin, press around it with a clean cloth — not on the bone."),
            ("Immobilise", "Support with padding, a sling (arm) or tie to the other leg with padding between."),
            ("Cold pack", "Ice wrapped in a cloth, 10–20 minutes. Never ice directly on skin."),
            ("Get medical help", "Hospital for an X-ray. Call 112 for major bones or if they can't be moved."),
        ],
        "when": ["Bone through the skin", "Thigh, hip, pelvis, neck or back injury",
                 "Limb is cold, pale or numb below the injury"],
        "dont": ["Don't try to straighten the bone", "Don't let them eat or drink (they may need surgery)",
                 "Don't move them if you suspect neck/back injury"],
    },
]
